### PR TITLE
Fixes https://github.com/kdschlosser/samsungctl/issues/72

### PR DESCRIPTION
**Pull request by p3g4asus**
As you asked, here it is the fix in a separate PR. The big one with the full python 2 compatibility will come when I am in front of the TV and I can make some last tests. If you want to have a look to the changes in the meanwhile, they are included in my encrypted_py2py3 branch.

### CODE REVIEW

**Comment by kdschlosser** [comment]
I checked out your updates.

suggestions...
here is a code example

```python

try:
    unicode = unicode
except NameError:
    unicode = bytes

def bytes2str(data):
    if isinstance(data, unicode):
        return data.decode('utf-8')
    else:
        return data

def debug(label, data):
    logging.debug(label + bytes2str(he(data)))
```
I think that if you directly convert each byte using chr() you may end up with values that are not supposed to be there. I am not sure why I think that I may have run across an issue doing that before I cannot remember off the top of my head. But the way it's done above will also take into consideration unicode for python 2

**Comment by p3g4asus** [comment]
Nice suggestion. I will edit my code accordingly. TY.

**Comment by kdschlosser** [comment]
I know you are still working on it. and if you can think of another way to go about it then awesome.

I did want to give you one heads up. I am not a HUGE fan of importing a specific item inside of a module. I would much rather see the whole module use. and no renaming of the import. It makes the code easier to follow.

example would be

    from binascii import unhexlify as uh,hexlify as he

   uh(var)
   he(var)

now imagine a file that has 2000 lines of code and you didn't write the code. how long do you think it would take you to figure out what uh and he was. imports are not always the first thing to get looked at.
if the call is not like what is below I am off and hunting for a module level function in the same file. not an import. if you do what is below. it is alot easier to know that the call is made to a function in another module. I can understand the want to press less keys when coding. But what I have learned is when you have to go back to fix something say a year later it will drive you nutz trying to figure out what you wrote.
better to use the long version.
so that is why I am not a not a huge fan of that type of coding.

    import binascii 

    binascii.unhexlify (var)
    binascii.hexlify (var)

another thing I am not really big on is what I like to call voodoo magic code.

here would be an example

```python
def in_data_1():
    pass

def in_data_2():
    pass

functions = {
    'data 10': in_data_1,
    'data 11':  in_data_2
}

def incoming_data1(data):
    functions[data]()

def incoming_data2(data):
    functions[data]()

def incoming_data3(data):
    functions[data]()

```

if there is again 2000 lines of code. this would be some smoke and mirrors. 


now I know this would be a pain in the ass if there was say 20 different data values and 20 different functions. But it is easier to follow. and maintain. not having to scroll all over the place back and forth and not really knowing what the returned data is.

I am all for combining like code. so the functions we call based on the incoming data  still remained because the code is shared between the different incoming data functions. just the use of the diction in favor of doing the if eliif was removed.

```python

def in_data_1():
    pass

def in_data_2():
    pass

def incoming_data1(data):
    if data ==  'data 10':
       in_data_1()
    elif data == 'data 11':
        in_data_2()

def incoming_data2(data):
    if data ==  'data 10':
        in_data_1()
    elif data == 'data 11':
        in_data_2()

def incoming_data3(data):
    if data ==  'data 10':
        in_data_1()
    elif data == 'data 11':
        in_data_2()
```

Now I also think supers are fine and dandy. so long as you do not use code like this

```python
class Class1(object):

    def run(self):
        if self.some_value == True:
            print("it's True")

class Class2(Class1):
    
    def __init__(self):
        self.some_value = True
        super(Class2, self).__init__()

```


if I am looking at Cl;ass1 that may be in a different file then Class2. how in the hell would I know where self.some_value is set?? off a hunting I would go.
that falls right into the voodoo magic code slot. I see that kind of thing all the time. It's hard as hell to know what is going on.

I have really grown to despise that kind of code, specifically because of a project I head up called EventGhost. If you want to see some nutty code go look at the source for that. I am not the original Author. and I would love to ask the original author what was on his melon when he wrote it. and because the program has been around for almost 15 years. i cannot change it to much or it will break the API for the 400+ plugins that are available for it. (and that is a whole other disaster)

things like to open up a simple settings dialog. the code is across no less then 15 files and subclass of a subclass of a subclass kind of a thing. and it has you bouncing all over the place if you need to follow the data trail to find out what may be changing something in a manner that is causing an error further down the line.

**Comment by kdschlosser** [comment]
Oh here is another perfect example. something I did in samsungctl.

```python

class RemoteMeta(type):

    def __call__(cls, conf):

        if isinstance(conf, dict):
            conf = Config(**conf)

        if conf.method == "legacy":
            remote = RemoteLegacy
        elif conf.method == "websocket":
            remote = RemoteWebsocket
        elif conf.method == "encrypted":
            if RemoteEncrypted is None:
                raise RuntimeError(
                    'Python 2 is not currently supported '
                    'for H and J model year TV\'s'
                )

            remote = RemoteEncrypted
        else:
            raise exceptions.ConfigUnknownMethod()


        class RemoteWrapper(remote, UPNPTV):

            def __init__(self, config):
                for name, key in KEYS.items():
                    self.__dict__[name] = KeyWrapper(self, key)

                remote.__init__(self, config)

                if (
                    config.upnp_locations is not None
                    and not config.upnp_locations
                ):
                    discover(config)

                print(config.upnp_locations)

                if config.upnp_locations:
                    UPNPTV.__init__(
                        self,
                        config.host,
                        config.upnp_locations,
                        self
                    )

                if config.path:
                    config.save()

            def __enter__(self):
                self.open()
                return self

            def __exit__(self, exc_type, exc_val, exc_tb):
                self.close()

        return RemoteWrapper(conf)


@six.add_metaclass(RemoteMeta)
class Remote(object):

    def __init__(self, config):
        self.config = config

```

smoke and mirrors.

this class does not a damned thing the __init__ never gets called all it does is a redirect to RemoteMeta and RemoteMeta then builds a wrapper class RemoteWrapper with parent classes added to it and that is what gets returned..

```python
class Remote(object):

    def __init__(self, config):
        self.config = config
```

the readable version of this would be to add the UPNPTV class as a parent class to RemoteLegacy RemoteEncrypted and RemoteWebsocket and duplicate the code in the __init__ of the RemoteWrapper class in each of those Remote classes. 

I did this because it was the least amount of code changes to achieve the same effect. Now that I know it will work properly I will be changing the code to the way that is easier to read.

**Comment by p3g4asus** [comment]
With your example with the RemoteMeta and RemoteWrapper classes, I got the idea. The code, as it is, it is a bit obfuscated and needs some additional time to understand what is doing. I had to spend quite some time to understand it despite the shortness of the code sample. Defining the classes separately maybe is less elegant and pythonic, but surely more functional. And can be done without duplicating many lines of code I think.

**Comment by kdschlosser** [comment]
I am the Administrator for EventGhost. I am the guy that pays the bills and keeps the lights on. I am the lead programmer, tho I have a guy that takes care of the GitHub end of things. He does the quality control on my PR's which is a full time job  LOL.

EventGhost It's written mostly in Python with some extension modules written in C

I didn't ask for the job. It kind of got handed to me. since then we moved to a KVM VPS server updated all of the website software.. MySql PHP Apache PHPbb things like that. upgraded EG so it is running Python 2,7 at the moment. we have builds that are running 3.5 as well as x86 and x64 variants. I have gotten EG to run as a service with no GUI.... we do have plans. the problem is the time. we have a rough draft plugin repository,

It's a lot to happen in a tad over 2 years. Plus I have to take care of support questions in the forum.

We have grown tho. gone from 200 unique site visits a day to almost 500. and went from a little over 5000 downloads of EG a year to almost 25 thousand.. I still have to give the website a facelift. But I have been so damned busy with things like getting openzwave to compile on windows. so we now have a zwave plugin. getting this library up to snuff so that we have the best samsung TV plugin. I still have to finish up my Sony TV plugin. and again that is another that will be the most complete control available

**Comment by kdschlosser** [comment]
I may just alter the UPNP_TV class to handle it. since all of the remote classes are going to be a subclass of it.

**Comment by p3g4asus** [comment]
You are officially my hero. I use Eventghost mostly with voice controls (with the help of google assistant page hosted on its web server plugin) and I like it so much.
It would be great for me to help in something if I could.
As for samsungctl maybe I can contribute with something more if you like/need. I have some code snippets to use the upnp method MainTVAgent2:GetChannelListURL to download and parse channel list, the method MainTVAgent2:SetMainTVChannel to change the channel and MainTVAgent2:GetCurrentMainTVChannel to retrieve the current channel. All tested and working.
Please tell me if you are interested in those snippets or if you want me to try to integrate them in samsungctl using a programming style as close as possible to yours, or if you are not interested. I would be happy to contribute if I can.

**Comment by kdschlosser** [comment]
OOOOh 

You really have not done any digging into the samsungctl library have you???


try this library out.... :smile:

https://github.com/kdschlosser/UPNP_Device/tree/develop

install it using 

    python setup,py install

to run it. you can do that from the command line

    upnp_device --help

and to just give a printout of all of the devices..

    upnp_device

or you can target a specific IP

    upnp_device 192.168.1.1

or more then one IP

    upnp_device 192.168.1.1 192.168.1.2

you can run the methods..

get the help for a specific function

    upnp_device --execute SomeUPNPClass.SomeUPNPFunction --help


passing parameters

    upnp_device --execute SomeUPNPClass.SomeUPNPFunction --SomeParameter SomeValue

it will print any returned data to the screen

**Comment by kdschlosser** [comment]
and you are more then welcome to help out with EventGhost if you want. you can help with the code. or you can help with the support end of things in the forum.. whatever it is you want to do. but me and my cohort that handle the GitHub end of things do not mind teaching. and explaining how thing work.

It is funny. because 3 years ago was the first time I ever used EG. and i was in the forum asking for help.. and no one answered me at all. I never programmed anything other then my VCR at that point. python?? what is that?? a snake??

I could see the usefulness in EventGhost. and to be honest it kind of pissed me off that i got no help. so i dug in and started learning. I also answered everyone that posted in thee forum. even if I had no clue what they were trying to do or what the problem was.. I would tell the person that when i answered.. and I also said to them. if you are patient we can learn how to fix or how to do.. and that is how things went for about a year or so.. The guy that was the maintainer at that point in time. he knew nothing about programming. he was given the website and the code to EventGhost by the original author before he walked away. and it was kind of stagnant. I simply started making a bunch of noise. and helping everyone.
next thing I know I am the administrator.

and now 3 years later.... this is where I am at.

**Comment by p3g4asus** [comment]
That is true, I did very few tests with upnp_device library. But the function of getting channel list and changing channels cannot be performed easyly that way. Infact to change channel you have to get its xml representation. To get it you have to download the channel list from the url returned from Getchannellisturl. The channel list is in binary format. You have to parse it and after that you get all the informations needed to create the xml representation of channels (that it is not practical to enter on the command line LOL). So in my opinion upnp library alone is quite unusable for the purpose.

**Comment by p3g4asus** [comment]
I am not used to ask for help. I usually start reading code and help myself. I am not patient to wait for other people's help. I will visit the forum and see what people ask and see if I can help.

**Comment by kdschlosser** [comment]
I know that... I was just showing you.. that whole library is apart of samsungctl..

samsungctl can change TV channel. it can also edit the OSD label for sources. as well as channels.
direct input of volume, mute, brightness, contrast, sharpness, aspect ratio. the whole deal..

you are gonna love this one...

```python

import samsungctl
config = samsungctl.Config.load('path/file')

with samsungctl.Remote(config) as remote:
    print(remote)
    print(remote.as_dict)
```

**Comment by kdschlosser** [comment]
import samsungctl
config = samsungctl.Config.load('path/file')

with samsungctl.Remote(config) as remote:
    for source in remote.sources:
        print(source.name, source.label, source.is_active)
        if source.name == 'HDMI1':
            source.activate()

        for channel in remote.channels:
            print(channel.name, channel.is_active)

**Comment by kdschlosser** [comment]
I have not hammered out the setting of the  TV channels. maybe that is something you want to take on.

**Comment by p3g4asus** [comment]
The second code snippets you posted gives me an AttributeError and complains that remote has no channels attribute. However I can add the channel management if you think it can be useful.

**Pull request merged**
